name: CSharp CI

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '8.0.x'
      - name: Run unit checks
        run: dotnet test Timesheet.Test --filter FullyQualifiedName~Timesheet.Test.Unit --logger trx --results-directory ./test-results
      - name: Run integration and E2E checks
        run: |
          dotnet run --project Timesheet &
          sleep 30 &&
          dotnet test Timesheet.Test --filter FullyQualifiedName~Timesheet.Test.Api --logger trx --results-directory ./test-results
          dotnet test Timesheet.Test --filter FullyQualifiedName~Timesheet.Test.E2E --logger trx --results-directory ./test-results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: always()
        with:
          files: |
            test-results/*.trx